/**:
  ros__parameters:
    base_frame_id: base_link
    odom_frame_id: odom
    cmd_vel_in_topic: /cmd_vel
    cmd_vel_out_topic: /cmd_vel_checked
    state_topic: /collision_monitor_state
    transform_tolerance: 0.5
    source_timeout: 1.0
    base_shift_correction: true
    stop_pub_timeout: 0.6

    polygons: ["FrontStopZone"]

    FrontStopZone:
      type: polygon
      points: "[[0.60, 0.07], [0.60, -0.07], [0.45, -0.07], [0.45, 0.07]]"
      action_type: stop
      min_points: 5
      visualize: false
      polygon_pub_topic: /collision_monitor/front_stop_zone
      enabled: true

    observation_sources: ["scan"]
    scan:
      type: scan
      topic: /agribot/lidar
      enabled: true
