# Goal
string mission_id
string zone_id
string plant_id
string fruit_id
string approach_waypoint_id
---
# Result
bool success
string harvest_event_id
uint32 basket_count
string message
---
# Feedback
string current_phase
float32 progress_pct
bool aligned_to_target
bool gripper_engaged
